# Generated by Django 4.2.7 on 2023-12-01 18:30

import DistribuidoraCarne.validaciones
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('estado', models.BooleanField(null=True, validators=[DistribuidoraCarne.validaciones.validar_estado])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_id])),
                ('nombre_cliente', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('apellido_cliente', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('rtn', models.CharField(max_length=14, validators=[DistribuidoraCarne.validaciones.validar_rtn])),
                ('direccion', models.CharField(max_length=150, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_correo])),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_descuento', models.CharField(max_length=50, unique=True)),
                ('descripción', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creación', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Descuentos',
                'verbose_name_plural': 'Descuentos',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=15)),
                ('nombre_empleado', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('apellido_empleado', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('fecha_nacimiento', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_fecha_nacimiento])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('correo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.correo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_impuesto', models.CharField(max_length=20)),
                ('descripción', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('valor_impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fecha_creación', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'impuesto',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_fecha_vencimiento])),
                ('cantidad', models.PositiveIntegerField(validators=[DistribuidoraCarne.validaciones.validar_Cantidad])),
                ('Stock_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stock_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_metodo_pago', models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
            ],
        ),
        migrations.CreateModel(
            name='ParametroSar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inicio', models.CharField(default='0001', max_length=5)),
                ('numero_fin', models.CharField(default='0005', max_length=5)),
            ],
            options={
                'verbose_name': 'Parámetros de Sar',
                'verbose_name_plural': 'Parámetros de Sar',
            },
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
            ],
        ),
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Identidad', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carro', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('chofer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.empleados')),
                ('ruta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.rutas')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('ciudad', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('direccion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('telefono', models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
                ('rtn', models.CharField(max_length=14, validators=[DistribuidoraCarne.validaciones.validar_rtn])),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.inventario')),
            ],
            options={
                'verbose_name': 'Surcusal',
                'verbose_name_plural': 'Surcusales',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('correo', models.CharField(max_length=65, null=True, validators=[DistribuidoraCarne.validaciones.validar_correo])),
                ('direccion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('rtn', models.CharField(max_length=14, validators=[DistribuidoraCarne.validaciones.validar_rtn])),
                ('nombre_contacto', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('celular_contacto', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('telefono', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.telefono')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('descripcion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('precio_venta', models.DecimalField(decimal_places=2, default=200, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_precio])),
                ('stock', models.PositiveIntegerField(validators=[DistribuidoraCarne.validaciones.validar_stock_actual])),
                ('estado', models.BooleanField(validators=[DistribuidoraCarne.validaciones.validar_estado])),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.categoria')),
                ('descuento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.descuento')),
                ('impuesto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.impuesto')),
                ('proveedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField()),
                ('total_pedido', models.FloatField(validators=[DistribuidoraCarne.validaciones.validar_total_pedido])),
                ('id_clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.clientes')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto'),
        ),
        migrations.CreateModel(
            name='HistoricalProducto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('descripcion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('precio_venta', models.DecimalField(decimal_places=2, default=200, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_precio])),
                ('stock', models.PositiveIntegerField(validators=[DistribuidoraCarne.validaciones.validar_stock_actual])),
                ('estado', models.BooleanField(validators=[DistribuidoraCarne.validaciones.validar_estado])),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='DistribuidoraCarne.categoria')),
                ('descuento', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='DistribuidoraCarne.descuento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('impuesto', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='DistribuidoraCarne.impuesto')),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='DistribuidoraCarne.proveedor')),
            ],
            options={
                'verbose_name': 'historical producto',
                'verbose_name_plural': 'historical productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalImpuesto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre_impuesto', models.CharField(max_length=20)),
                ('descripción', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('valor_impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fecha_creación', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical impuesto',
                'verbose_name_plural': 'historical impuestos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEmpleados',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('documento', models.CharField(max_length=15)),
                ('nombre_empleado', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('apellido_empleado', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('fecha_nacimiento', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_fecha_nacimiento])),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('correo', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='DistribuidoraCarne.correo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='DistribuidoraCarne.sucursal')),
                ('telefono', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='DistribuidoraCarne.telefono')),
                ('tipo_cargo', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='DistribuidoraCarne.tipocargo')),
                ('tipo_documento', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='DistribuidoraCarne.tipodocumento')),
            ],
            options={
                'verbose_name': 'historical Empleado',
                'verbose_name_plural': 'historical Empleados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDescuento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre_descuento', models.CharField(db_index=True, max_length=50)),
                ('descripción', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creación', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Descuentos',
                'verbose_name_plural': 'historical Descuentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClientes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('documento', models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_id])),
                ('nombre_cliente', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('apellido_cliente', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('rtn', models.CharField(max_length=14, validators=[DistribuidoraCarne.validaciones.validar_rtn])),
                ('direccion', models.CharField(max_length=150, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('correo', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='DistribuidoraCarne.correo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('telefono', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='DistribuidoraCarne.telefono')),
                ('tipo_documento', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='DistribuidoraCarne.tipodocumento')),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'verbose_name_plural': 'historical Clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FacturaEncabezado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField()),
                ('rango_inicial_factura', models.IntegerField()),
                ('rango_final_factura', models.IntegerField()),
                ('cai', models.CharField(max_length=32, unique=True, validators=[DistribuidoraCarne.validaciones.validar_cai])),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.sucursal')),
                ('parametros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.parametrosar')),
            ],
            options={
                'verbose_name': 'Encabezado Factura',
                'verbose_name_plural': 'Encabezado Facturas',
            },
        ),
        migrations.CreateModel(
            name='FacturaDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.facturaencabezado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.inventario')),
            ],
            options={
                'verbose_name': 'Detalle Factura',
                'verbose_name_plural': 'Detalles Facturas',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('direccion_entrega', models.CharField(blank=True, max_length=255, null=True, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('carro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.transporte')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.sucursal'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='telefono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.telefono'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='tipo_cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.tipocargo'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='tipo_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.tipodocumento'),
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[DistribuidoraCarne.validaciones.validar_Cantidad])),
                ('descripcion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('fecha_devolucion', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_date_time])),
                ('id_producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto')),
            ],
            options={
                'verbose_name': 'Devolucion',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cotizacion', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_fecha_actualizacion])),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.clientes')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='ComprasEncabezado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_factura', models.CharField(max_length=100)),
                ('fecha_compra', models.DateField(blank=True, null=True, validators=[DistribuidoraCarne.validaciones.validar_date_time])),
                ('observacion', models.TextField(blank=True, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ComprasDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField(default=0)),
                ('precio_compra', models.FloatField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.comprasencabezado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.inventario')),
            ],
            options={
                'verbose_name': 'Detalle Compra',
                'verbose_name_plural': 'Detalles Compras',
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.correo'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.telefono'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tipo_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.tipodocumento'),
        ),
    ]
