# Generated by Django 4.2.7 on 2023-12-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadet',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
