# Generated by Django 4.2.7 on 2023-12-06 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'Detalle Venta', 'verbose_name_plural': 'Detalles ventas'},
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='facturadet',
            name='producto',
        ),
        migrations.AddField(
            model_name='facturadet',
            name='detalle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.detalleventa'),
            preserve_default=False,
        ),
    ]
