# Generated by Django 4.2.7 on 2023-12-06 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0002_alter_detalleventa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturadet',
            name='detalle',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='detalle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.facturadet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturadet',
            name='producto',
            field=models.ManyToManyField(through='DistribuidoraCarne.DetalleVenta', to='DistribuidoraCarne.inventario'),
        ),
    ]
