# Generated by Django 5.0 on 2023-12-10 03:52

import DistribuidoraCarne.validaciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0003_remove_facturadet_detalle_detalleventa_detalle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devoluciones',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rutas',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterField(
            model_name='comprasdetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_Cantidad]),
        ),
        migrations.AlterField(
            model_name='comprasdetalle',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_precio]),
        ),
        migrations.AlterField(
            model_name='comprasdetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_Total_Cotizacion]),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='nombre_descuento',
            field=models.CharField(max_length=20, unique=True, validators=[DistribuidoraCarne.validaciones.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_Cantidad]),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, validators=[DistribuidoraCarne.validaciones.validar_fecha_no_pasado]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tarjeta',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[DistribuidoraCarne.validaciones.validar_numero_tarjeta]),
        ),
        migrations.AlterField(
            model_name='facturadet',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_valor_impuesto]),
        ),
        migrations.AlterField(
            model_name='historicaldescuento',
            name='nombre_descuento',
            field=models.CharField(db_index=True, max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='historicalimpuesto',
            name='nombre_impuesto',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='historicalimpuesto',
            name='valor_impuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[DistribuidoraCarne.validaciones.validar_valor_impuesto]),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='nombre_impuesto',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='valor_impuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[DistribuidoraCarne.validaciones.validar_valor_impuesto]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Stock_maximo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_nivel_maximo_stock]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Stock_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_nivel_minimo_stock]),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='ruta',
            field=models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_descripcion]),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(default='Identidad', max_length=50, validators=[DistribuidoraCarne.validaciones.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='codigo',
            field=models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_placa_honduras]),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='nombre_carro',
            field=models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_nombre]),
        ),
    ]
