# Generated by Django 4.2.7 on 2023-11-18 19:57

import DistribuidoraCarne.validaciones
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('estado', models.BooleanField(null=True, validators=[DistribuidoraCarne.validaciones.validar_estado])),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(default='0801199900123', max_length=15)),
                ('nombre_cliente', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('direccion', models.CharField(max_length=150, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_correo])),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(default='0801199900123', max_length=15)),
                ('nombre_empleado', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('fecha_nacimiento', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_fecha_nacimiento])),
                ('correo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.correo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_impuesto', models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('tipo_impuesto', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('valor_impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[DistribuidoraCarne.validaciones.validar_valor_impuesto])),
            ],
            options={
                'db_table': 'impuesto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('telefono', models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
                ('correo', models.CharField(max_length=65, null=True, validators=[DistribuidoraCarne.validaciones.validar_correo])),
                ('direccion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('rtn', models.CharField(max_length=14, validators=[DistribuidoraCarne.validaciones.validar_rtn])),
                ('celular_contacto', models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
                ('fecha_registro', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_date_time])),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_surcusal', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('ciudad', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('direccion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('telefono', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
            ],
            options={
                'verbose_name': 'Surcusal',
                'verbose_name_plural': 'Surcusales',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
            ],
        ),
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('descripcion', models.CharField(max_length=200, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateField(auto_now_add=True, validators=[DistribuidoraCarne.validaciones.validar_fecha_actualizacion])),
                ('ultima_actualizacion', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_fecha_actualizacion])),
                ('descripcion_actualizacion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('fecha_agregado', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField()),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.categoria')),
                ('impuesto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.impuesto')),
                ('proveedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Precio Histórico',
                'verbose_name_plural': 'Precios Históricos',
            },
        ),
        migrations.CreateModel(
            name='Parametros_impuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(auto_now_add=True, validators=[DistribuidoraCarne.validaciones.validar_fecha_actualizacion])),
                ('fecha_final', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_fecha_actualizacion])),
                ('id_impuesto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.impuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('cantidad', models.PositiveIntegerField()),
                ('nivel_minimo_stock_inventario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivel_maximo_stock_inventario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto')),
                ('sucursal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('nombre_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.empleados')),
                ('tipo_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.tipocargo')),
            ],
        ),
        migrations.CreateModel(
            name='EncabezadoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surcusal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.sucursal')),
            ],
            options={
                'db_table': 'encabezado_factura',
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.sucursal'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='telefono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.telefono'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='tipo_cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.tipocargo'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='tipo_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.tipodocumento'),
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('fecha_devolucion', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_date_time])),
                ('id_producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto')),
            ],
            options={
                'verbose_name': 'Devolucion',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cotizacion', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_date_time])),
                ('total_cotizacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.clientes')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.correo'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.telefono'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tipo_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.tipodocumento'),
        ),
    ]
