# Generated by Django 4.2.7 on 2023-11-10 02:15

import DistribuidoraCarne.validaciones
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('stock_actual', models.CharField(max_length=4, validators=[DistribuidoraCarne.validaciones.validar_stock_actual])),
                ('estado', models.BooleanField(null=True, validators=[DistribuidoraCarne.validaciones.validar_estado])),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_id])),
                ('nombre_cliente', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('telefono', models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
                ('rtn', models.CharField(max_length=14, validators=[DistribuidoraCarne.validaciones.validar_rtn])),
                ('correo', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_correo])),
                ('direccion', models.CharField(max_length=150, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
                ('correo', models.CharField(max_length=65, null=True, validators=[DistribuidoraCarne.validaciones.validar_correo])),
                ('direccion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('rtn', models.CharField(max_length=14, validators=[DistribuidoraCarne.validaciones.validar_rtn])),
                ('nombre_proveedor', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('celular_contacto', models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
                ('fecha_registro', models.DateField(auto_now_add=True, validators=[DistribuidoraCarne.validaciones.validar_date_time])),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_surcusal', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('ciudad', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('direccion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('telefono', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
            ],
            options={
                'verbose_name': 'Surcusal',
                'verbose_name_plural': 'Surcusales',
            },
        ),
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('descripcion', models.CharField(max_length=200, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_salario_base])),
                ('fecha_creacion', models.DateField(auto_now_add=True, validators=[DistribuidoraCarne.validaciones.validar_fecha_actualizacion])),
                ('ultima_actualizacion', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_fecha_actualizacion])),
                ('descripcion_actualizacion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Identidad', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('descripcion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=150, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_salario])),
                ('precio_venta', models.DecimalField(decimal_places=2, default=200, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_salario])),
                ('stock', models.PositiveIntegerField(validators=[DistribuidoraCarne.validaciones.validar_stock_actual])),
                ('fecha_agregado', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_date_time])),
                ('estado', models.BooleanField(validators=[DistribuidoraCarne.validaciones.validar_estado])),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.categoria')),
                ('proveedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Inventario', max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('fecha_entrada', models.DateTimeField(validators=[DistribuidoraCarne.validaciones.validar_date_time])),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.PositiveIntegerField(validators=[DistribuidoraCarne.validaciones.validar_Cantidad])),
                ('nivel_minimo_stock_inventario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivel_maximo_stock_inventario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_id])),
                ('nombre_empleado', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('fecha_nacimiento', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_fecha_nacimiento])),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_salario])),
                ('email', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_correo])),
                ('telefono', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
                ('direccion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('surcusal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.sucursal')),
                ('tipo_cargo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.tipocargo')),
                ('tipo_documento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.tipodocumento')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[DistribuidoraCarne.validaciones.validar_Cantidad])),
                ('descripcion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('fecha_devolucion', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_date_time])),
                ('id_producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto')),
            ],
            options={
                'verbose_name': 'Devolucion',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cotizacion', models.DateField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_date_time])),
                ('total_cotizacion', models.DecimalField(decimal_places=2, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_Total_Cotizacion])),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.clientes')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='tipo_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.tipodocumento'),
        ),
    ]
