# Generated by Django 4.2.7 on 2023-11-08 03:17

import DistribuidoraCarne.validaciones
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('estado', models.BooleanField(null=True, validators=[DistribuidoraCarne.validaciones.validar_estado])),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
                ('correo', models.CharField(max_length=65, null=True, validators=[DistribuidoraCarne.validaciones.validar_correo])),
                ('direccion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('rtn', models.CharField(max_length=14, validators=[DistribuidoraCarne.validaciones.validar_rtn])),
                ('nombre_proveedor', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('celular_contacto', models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
                ('fecha_registro', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_date_time])),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_surcusal', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('ciudad', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('direccion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('telefono', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
            ],
        ),
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Empleado', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Identidad', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('descripcion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_descripcion])),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('fecha_agregado', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_date_time])),
                ('estado', models.BooleanField(validators=[DistribuidoraCarne.validaciones.validar_estado])),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.categoria')),
                ('proveedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('nivel_minimo_stock_inventario', models.DecimalField(decimal_places=2, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_nivel_minimo_stock])),
                ('nivel_maximo_stock_inventario', models.DecimalField(decimal_places=2, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_nivel_maximo_stock])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(default='0801199900123', max_length=15)),
                ('nombre_empleado', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('fecha_nacimiento', models.DateField(validators=[DistribuidoraCarne.validaciones.validar_fecha_nacimiento])),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_salario])),
                ('email', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_correo])),
                ('telefono', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
                ('direccion', models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('surcusal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.sucursal')),
                ('tipo_cargo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.tipocargo')),
                ('tipo_documento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.tipodocumento')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(default='0801199900123', max_length=15)),
                ('nombre_cliente', models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre])),
                ('telefono', models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_telefono])),
                ('correo', models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_correo])),
                ('direccion', models.CharField(max_length=150, validators=[DistribuidoraCarne.validaciones.validar_direccion])),
                ('tipo_documento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.tipodocumento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
