# Generated by Django 4.2.7 on 2023-11-11 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncabezadoFactura',
            fields=[
                ('id_encabezado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_negocio', models.CharField(max_length=200)),
                ('direccion_negocio', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('rtn', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'encabezado_factura',
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id_impuesto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_impuesto', models.CharField(max_length=50)),
                ('nombre_impuesto', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'impuesto',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo_pago', models.CharField(max_length=255)),
                ('tipo_metodo_pago', models.CharField(max_length=50)),
                ('numero_tarjeta', models.CharField(max_length=255)),
                ('fecha_vencimiento', models.DateField()),
                ('cvv', models.CharField(max_length=10)),
                ('nombre_titular', models.CharField(max_length=255)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.clientes')),
            ],
            options={
                'db_table': 'metodo_pago',
            },
        ),
    ]
