# Generated by Django 4.2.7 on 2023-11-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(default='Inventario', max_length=65),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nivel_maximo_stock_inventario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nivel_minimo_stock_inventario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
