# Generated by Django 4.2.7 on 2023-11-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0004_alter_encabezadofactura_nombre_negocio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='nombre_metodo_pago',
        ),
    ]
